name: unraider_compile

on:
  workflow_dispatch:
      

permissions:
  contents: read

jobs:
  build_unraider:
    name: Build Unraider
    runs-on: ubuntu-latest
    steps:
      - name: space cleanup and initiallzation environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo apt-get install libudev-dev -y

      - name: checkout source code
        uses: actions/checkout@v3

      - name: checkout patchelf
        run: |
          git submodule update --init --recursive

      - name: compile
        run: |
          make clean && make all && make all VERSION=6.11.5
          mkdir -p ./artifacts/6.11.5/ ./artifacts/6.12.2/
          cp -rf ./6.11.5/unraider ./artifacts/6.11.5
          cp -rf ./6.12.2/unraider ./artifacts/6.12.2
          # cp -rf ./src/hook.so ./artifacts
          # cp -rf ./code ./artifacts

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: unraider_hook
          path: ./artifacts