# release.yml
# Builds and creates the release on any tags starting with a `v`
name: unraider release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tags:
        description: "tags"
        required: true
        type: string
      ssh:
        description: "SSH connection to Actions"
        required: false
        type: choice
        default: "false"
        options:
          - "true"
          - "false"
jobs:
  compile:
    uses: ./.github/workflows/compile.yml
    with:
      ssh: "false"

  release:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: unraider
          path: artifacts

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: |
            artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN}}
